### ISSUE TITLE
had to downgrade to 1.5.7 from 1.5.12 .. errors occuring at 1.5.8 and above

### ISSUE THREAD

**Issue by zifahm** [graphcool/prisma-binding#112]
this is the error i am getting if i had binding at 1.5.8 and above so i had to downgrade to 1.5.7 !!
how do solve this issue?

`Cannot use GraphQLSchema "[object Object]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf ( /Documents/server/node_modules/graphql/jsutils/instanceOf.js:17:13)
    at isSchema  /Documents/server/node_modules/graphql/type/schema.js:48:35)
    at validateSchema ( /Documents/server/node_modules/graphql/type/validate.js:51:25)
    at assertValidSchema  /Documents/server/node_modules/graphql/type/validate.js:76:16)
    at Object.validate ( /Documents/server/node_modules/graphql/validation/validate.js:61:35)
    at doRunQuery  /Documents/server/node_modules/apollo-server-core/dist/runQuery.js:88:38)
    at /Documents/server/node_modules/apollo-server-core/dist/runQuery.js:22:54
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)`

**Comment by marktani** [comment]
hey @zifahm, could you try [following these steps](https://github.com/graphcool/graphql-yoga/issues/162#issuecomment-367368045)? 🙂

Please let me know if that doesn't resolve the issue.
Thanks! 🙏

**Comment by zifahm** [comment]
@marktani  I get this error now , Unexpected token < in JSON at position 0

**Comment by zifahm** [comment]
had to update prisma-binding to latest , and do npm i  , solved the issue :+1:
