### ISSUE TITLE
`Prisma` constructor should work without a `secret` option being provided 

### ISSUE THREAD

**Issue by nikolasburk** [graphcool/prisma-binding#141]
When trying to instantiate a `Prisma` instance without a secret like this:

```js
const server = new GraphQLServer({
  typeDefs: './src/schema.graphql',
  resolvers,
  context: req => ({
    ...req,
    db: new Prisma({
      typeDefs: 'src/generated/prisma.graphql', // the auto-generated GraphQL schema of the Prisma API
      endpoint: 'https://eu1.prisma.sh/public-bristlegriffin-942/nb-test-2/dev',          // the endpoint of the Prisma API
      debug: true,                              // log all GraphQL queries & mutations sent to the Prisma API
    }),
  }),
})
```

I'm getting this error message:

```
Server is running on http://localhost:4000
Error: No Prisma secret found. Please provide the `secret` constructor option.
    at new Prisma (/Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/prisma-binding/dist/src/Prisma.js:78:19)
    at GraphQLServer.context (/Users/nburk/Desktop/test-projects/node/nb-test-2/src/index.js:48:9)
    at GraphQLServer.<anonymous> (/Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/graphql-yoga/dist/src/index.js:201:51)
    at step (/Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/graphql-yoga/dist/src/index.js:40:23)
    at Object.next (/Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/graphql-yoga/dist/src/index.js:21:53)
    at /Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/graphql-yoga/dist/src/index.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/graphql-yoga/dist/src/index.js:11:12)
    at /Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/graphql-yoga/dist/src/index.js:194:118
    at /Users/nburk/Desktop/test-projects/node/nb-test-2/node_modules/apollo-server-core/dist/graphqlOptions.js:52:40
```

**Comment by nikolasburk** [comment]
👏 ⚡️
