### ISSUE TITLE
Wrong argument not detected

### ISSUE THREAD

**Issue by marktani** [graphcool/prisma-binding#55]
```js
  const roleIds = ['id1', 'id2'];
  const data = {
    roles: { connect: { id: roleIds } },
  };
  return ctx.db.mutation.createMembership({ data }, info);
```

returns this error:

```sh
[GraphQL error]: Message: No Node for the model Role with value id1,id2 for id found., Location: [object Object], Path: createMembership
Error: No Node for the model Role with value id1,id2 for id found.
    at Object.checkResultAndHandleErrors (/my-app/node_modules/graphql-tools/dist/stitching/errors.js:69:36)
    at Object.<anonymous> (/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:92:52)
    at step (/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:40:23)
    at Object.next (/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:21:53)
    at fulfilled (/my-app/node_modules/graphql-tools/dist/stitching/delegateToSchema.js:12:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Note

> No Node for the model Role with value **id1,id2** for id found.

It looks like `graphcool-binding` is converting the list of strings that was passed into the `id` argument to a single string, instead of either throwing an error or passing the list of strings onto the GraphQL API.

see here for more information: https://www.graph.cool/forum/t/connect-mutation-for-many-to-many/2074?u=nilan

**Comment by schickling** [comment]
Can you confirm this by pasting the generated query using the `debug: true` binding option?

**Comment by marktani** [comment]
Yes, I'm looking into creating a reproduction example.

**Comment by kbrandwijk** [comment]
Anything to repro this already @marktani?

**Comment by marktani** [comment]
Nope, closing this for lack of reproduction.
